version: "3.5"

services:
  database:
    image: postgis/postgis:15-3.3
    container_name: fwm-postgres
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    volumes:
      - ../data/database/:/var/lib/postgresql/data
    networks:
      - directus

  cache:
    container_name: fwm-cache
    restart: always
    image: redis:6
    networks:
      - directus

  directus:
    image: directus/directus:${DIRECTUS_VERSION}
    container_name: fwm-directus
    restart: unless-stopped
    ports:
      - 8055:8055
    volumes:
      - ../data/cms/uploads:/directus/uploads
      - ../data/cms/extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      ACCESS_TOKEN_TTL: '15m'
      EXTENSIONS_AUTO_RELOAD: 'true'
      REFRESH_TOKEN_TTL: '365d'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      FILES_MAX_UPLOAD_SIZE: '10mb'
      MAX_PAYLOAD_SIZE: '10mb'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - directus
  
  node:
    build:
      context: ./fwm-crawlers
      dockerfile: prod.Dockerfile
      args:
        EXPRESS_PORT: ${EXPRESS_PORT}
        DIRECTUS_API: ${DIRECTUS_API}
        OPENWEATHER_KEY: ${OPENWEATHER_KEY}
        DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}
        FORECAST_OUTPUT_JSON_FOLDER: ${FORECAST_OUTPUT_JSON_FOLDER}
        BSKY_USERNAME: ${BSKY_USERNAME}
        BSKY_PASSWORD: ${BSKY_PASSWORD}
    container_name: fwm-crawlers
    restart: unless-stopped
    hostname: fwm-crawlers
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    volumes:
      - ../fwm-crawlers/:/app/
      - ../data/forecasts/:/app/forecasts/
    networks:
      - directus
    depends_on:
      - python-service

  python-service:
    build:
      context: ./fwm-python
      dockerfile: prod.Dockerfile
      args:
        PYTHON_PORT: ${PYTHON_PORT}
    container_name: fwm-python-service
    restart: unless-stopped
    ports:
      - ${PYTHON_PORT}:${PYTHON_PORT}
    volumes:
      - ../data/forecasts/:/forecasts/
    networks:
      - directus

networks:
  directus:
    name: directus
    driver: bridge