version: '3.8'
services:
  dwd_downloader:
    image: 'virtuosofriend/iconeu-downloader:latest'
    container_name: dwd_forecastdownloader
    environment:
      - TIMESTAMP=${TIMESTAMP}
      - PRODUCTS=${SINGLE_LEVEL_FIELDS}
      - MAX_TIME=${MAX_TIME}
      - DESTINATION_FOLDER=/data
    volumes:
      - ../../data/forecasts/:/data
    user: '${UID}:${GID}'
    networks:
      - downloader

networks:
  downloader:
    name: downloader
    driver: bridge