FROM node:17.7.2-alpine3.15

ARG EXPRESS_PORT
ARG DIRECTUS_API
ARG OPENWEATHER_KEY
ARG DIRECTUS_TOKEN
ENV EXPRESS_PORT=${EXPRESS_PORT}
ENV DIRECTUS_API=${DIRECTUS_API}
ENV OPENWEATHER_KEY=${OPENWEATHER_KEY}
ENV DIRECTUS_TOKEN=${DIRECTUS_TOKEN}

# Set the working directory
WORKDIR /app

# Expose the port
EXPOSE ${EXPRESS_PORT}

# Start the application
CMD ["npm", "run", "start"]